version: "3.9"

services:
  postgres-test:
    container_name: knex-native-enums
    image: postgres:16.1
    environment:
      POSTGRES_USER: "${DB_USER_TEST}"
      POSTGRES_PASSWORD: "${DB_PASSWORD_TEST}"
      POSTGRES_DB: "${DB_NAME_TEST}"
    ports:
      - "${DB_PORT_TEST}:5432"
    restart: unless-stopped
    env_file:
      - .env
